version: '3.4'
services:

  react:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: react
    command: ["yarn", "next", "-p", "8083"]
    ports:
      - 8083:8083
    volumes:
      - ./src/app:/usr/src/app
    networks:
      - go_api

networks:
  go_api:
    external: true